Copied website
ej-pixel/treinamento-bits-2019-1 pull request #10
Opened 2019-06-11 00:06 UTC by gorgonun

2019-06-12 05:26 UTC, ej-pixel requested changes
Patrick, o seu resultado ficou ótimo!
Mas como a ideia de grid e flex é evitar aquele monte de margin e etc, eu fiz uma sugestão de como você poderia ter feito o final do bottom e a correção do seu botão. Dê uma olhada no que você acha.

2019-06-12 21:47 UTC, gorgonun commented
Eu achei legal o resultado, apesar da margem no #minhanadarte ter ficado um pouco fora do que está no site

2019-06-13 02:00 UTC, ej-pixel commented
Você vai querer alterar alguma coisa ou posso dar merge?

2019-06-13 02:22 UTC, gorgonun commented
Pode dar merge

2019-06-18 04:32 UTC, merged